name: "Setup PHP and Mysql"

inputs:
  php_version:
    description: 'The PHP version to run'
    default: '7.4'
    required: false
  composer_install_options:
    required: false
    default: '--no-progress --prefer-dist --optimize-autoloader'
    description: "Custom composer install options"
  sd_github_access_token:
    description: 'Access token to set before running composer.'
    default: 'false' #a bit hacky
    required: false

runs:
  using: "composite"
  steps:

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        ini-values: ${{ inputs.php_ini-values }}
        coverage: ${{ inputs.php_coverage }}
        tools: ${{ inputs.php_tools }}

    - name: Is there a config file?
      run: |
        if [[ ! -f "phpstan.neon" ]]; then
        wget https://raw.githubusercontent.com/frittsnl/github-actions/master/larastan/phpstan.neon
        fi
      shell: bash

    ### If not supported (yet) https://github.com/actions/runner/issues/834
    - name: Link github token to composer; allows accesing sundata-package on github
      run: |
        if echo ${{ inputs.sd_github_access_token }} | grep -c "false"
        then
          echo "No key to set for composer"
        else
          composer config -g github-oauth.github.com ${{ inputs.sd_github_access_token }}
        fi
      shell: bash

    - name: Install Composer dependencies
      run: composer install ${{ inputs.composer_install_options }}
      shell: bash

    - name: Install phpstan
      run: |
        composer require spaze/phpstan-disallowed-calls nunomaduro/larastan:^1.4 ${{ inputs.composer_install_options }}
      shell: bash
