name: "Setup PHP and Mysql"

inputs:
  php_version:
    description: "The PHP version to run"
    default: '7.4'
    required: false
  mysql_version:
    description: "The MySQL version to run"
    default: '5.7'
    required: false
  db_name:
    description: "The DB name. Default is [test_db]"
    required: false
    default: 'test_db'
  db_username:
    description: "The DB username. Default is [test_user]"
    required: false
    default: 'test_user'
  db_password:
    required: false
    default: 'test_password'
    description: "The DB password. Default is [test_password]"
  db_port:
    description: "The DB port. Default is [3306]"
    required: false
    default: '3306'
  sd_github_access_token:
    description: 'Access token to set before running composer.'
    default: 'false' #a bit hacky
    required: false
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage:
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
  composer_install_options:
    required: false
    default: '--no-progress --prefer-dist --optimize-autoloader'
    description: "Custom composer install options"

runs:
  using: "composite"
  steps:

    - name: Test defaults
      run: echo ${{ inputs.mysql_version }}
      shell: bash

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      shell: bash

    - name: "Setup MySQL"
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: ${{ inputs.db_port }}
        container port: ${{ inputs.db_port }}
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: ${{ inputs.mysql_version }}
        mysql database: ${{ inputs.db_name }}
        mysql user: ${{ inputs.db_username }}
        mysql password: ${{ inputs.db_password }}

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        ini-values: ${{ inputs.php_ini-values }}
        coverage: ${{ inputs.php_coverage }}
        tools: ${{ inputs.php_tools }}

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      shell: bash

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-PHP${{ inputs.php_version }}-composer-

### If not supported (yet) https://github.com/actions/runner/issues/834
    - name: Link github token to composer; allows accesing sundata-package on github
      run: |
        if echo ${{ inputs.sd_github_access_token }} | grep -c "false"
        then
          echo "No key to set for composer"
        else
          composer config -g github-oauth.github.com ${{ inputs.sd_github_access_token }}
        fi
      shell: bash

    - name: Install Composer dependencies
      run: composer install ${{ inputs.composer_install_options }}
      shell: bash

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=${{ inputs.db_password }} --user=${{ inputs.db_username }} --port=${{ inputs.db_port }} --silent
        do
            echo "Waiting for MySQL..."
            ((count++)) && ((count==30)) && break
            sleep 1
        done
      shell: bash

    - name: Debug MySQL version
      run: mysql --host=127.0.0.1 -u ${{ inputs.db_username }} -p${{ inputs.db_password }} --port=${{ inputs.db_port }} -e "SHOW VARIABLES LIKE \"%version%\";"
      shell: bash

    - name: Debug PHP version
      run: php -v
      shell: bash
